name: Daily Data Update

on:
  schedule:
    # Run daily at 5 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch:  # Allow manual triggering
    
jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      - name: Run data update script
        run: python backend/update_data.py
      
      - name: Copy data to frontend
        run: python backend/copy_data_to_frontend.py
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Commit and push updated data
        run: |
          git add data/ frontend/public/data/
          git diff --staged --quiet || git commit -m "Update data files (automated)"
          git push